**Alunos:**

* Arthur Franco
* Firmo de Assis
* Nadege de Melo

### Numpy

In [2]:
%pip install -q --upgrade numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

1 - Utilize o método `numpy.info` para obter informações do método `numpy.add`.

In [4]:
# Insira a resposta abaixo.
# o método numpy.info se comporta como o help()
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

2 - Utilize a função *range* do python para criar automaticamente uma lista de números variando de 0 até 15.

In [5]:
# Insira a resposta abaixo.
listaQ1 = list(range(0, 16))

print(f"Lista de números: {listaQ1}")

Lista de números: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]


3 - Converta a lista criada para um objeto do tipo numpy array.

In [6]:
# Insira a resposta abaixo.
npQ3 = np.array(listaQ1)

print(f"Lista de números convertida em array: {npQ3}")

Lista de números convertida em array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


4 - Crie um  novo array equivalente ao anterior utilizando diretamente os recursos do numpy.

In [7]:
# Insira a resposta abaixo.
npQ4 = np.arange(0, 16)

print(f"Array de números equivalente: {npQ4}")

Array de números equivalente: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


5 - A partir do último array utilizado anteriormente, realize os seguintes procedimentos:

1. Exiba o formato atual do array.
2. Altere o formato para (4, 4).
3. Exiba novamente o formato do array após redimensioná-lo.

In [8]:
# Insira a resposta abaixo.

# Passo 1
print(f"O formato atual do arrey: {npQ4.shape} \n")

# Passo 2
npQ4_Novo = npQ4.reshape(4, 4)

# Passo 3
print(f"O novo formato do arrey: {npQ4_Novo.shape}")

O formato atual do arrey: (16,) 

O novo formato do arrey: (4, 4)


6 - Compute a média, mediana e o desvio padrão do array resultante da questão anterior.

In [9]:
# Insira a resposta abaixo.
npQ6_mean = np.mean(npQ4_Novo)
npQ6_median = np.median(npQ4_Novo)
npQ6_std = np.std(npQ4_Novo)

print(f"A média do arrey é {npQ6_mean}, a sua mediana é {npQ6_median} e o seu desvio padrão é {npQ6_std}")

A média do arrey é 7.5, a sua mediana é 7.5 e o seu desvio padrão é 4.6097722286464435


7 - Crie uma cópia do array atual  e transforme todos os números em valores negativos.

In [10]:
# Insira a resposta abaixo.
npQ7 = npQ4_Novo.copy()
npQ7 *= -1

print(f"Array atual com números negativos: \n {npQ7}")

Array atual com números negativos: 
 [[  0  -1  -2  -3]
 [ -4  -5  -6  -7]
 [ -8  -9 -10 -11]
 [-12 -13 -14 -15]]


8 - Realize os seguintes procedimentos:

1. Concatene verticalmente (*row-wise*) o array de números positivos com o array de números negativos.

2. Concatene horizontalmente (*column-wise*) o array resultante do passo 1 com ele mesmo.

3. Concatene em profundidade três cópias do array resultante do passo anterior, exibindo o formato final.

Como fazer?

> Analise a documentação das funções `stack`, `hstack` e `dstack` da biblioteca numpy.

In [29]:
# Insira a resposta abaixo.

# Passo 1
np_row = np.stack((npQ4_Novo, npQ7), axis = 0)
print(f"Concatenação vertical: \n {np_row} \n")

# Passo 2
np_column = np.hstack((np_row[0], np_row[1]))
print(f"Concatenação horizontal: \n {np_column} \n")

# Passo 3
np_deep = np.dstack((np_column, np_column, np_column))
print(f"Concatenação de profundidade: \n {np_deep} \n")
print(f"Formato final: {np_deep.shape}")

Concatenação vertical: 
 [[[  0   1   2   3]
  [  4   5   6   7]
  [  8   9  10  11]
  [ 12  13  14  15]]

 [[  0  -1  -2  -3]
  [ -4  -5  -6  -7]
  [ -8  -9 -10 -11]
  [-12 -13 -14 -15]]] 

Concatenação horizontal: 
 [[  0   1   2   3   0  -1  -2  -3]
 [  4   5   6   7  -4  -5  -6  -7]
 [  8   9  10  11  -8  -9 -10 -11]
 [ 12  13  14  15 -12 -13 -14 -15]] 

Concatenação de profundidade: 
 [[[  0   0   0]
  [  1   1   1]
  [  2   2   2]
  [  3   3   3]
  [  0   0   0]
  [ -1  -1  -1]
  [ -2  -2  -2]
  [ -3  -3  -3]]

 [[  4   4   4]
  [  5   5   5]
  [  6   6   6]
  [  7   7   7]
  [ -4  -4  -4]
  [ -5  -5  -5]
  [ -6  -6  -6]
  [ -7  -7  -7]]

 [[  8   8   8]
  [  9   9   9]
  [ 10  10  10]
  [ 11  11  11]
  [ -8  -8  -8]
  [ -9  -9  -9]
  [-10 -10 -10]
  [-11 -11 -11]]

 [[ 12  12  12]
  [ 13  13  13]
  [ 14  14  14]
  [ 15  15  15]
  [-12 -12 -12]
  [-13 -13 -13]
  [-14 -14 -14]
  [-15 -15 -15]]] 

Formato final: (4, 8, 3)


9 - Utilize o array do passo 1 da questão anterior e transforme os valores da segunda e terceira colunas em 1.

In [ ]:
# Insira a resposta abaixo.
np_row[:, :, 1:3] = 1

print(f"Novo arrey: \n {np_row}")

Novo arrey do passo 1 
 [[[  0   1   1   3]
  [  4   1   1   7]
  [  8   1   1  11]
  [ 12   1   1  15]]

 [[  0   1   1  -3]
  [ -4   1   1  -7]
  [ -8   1   1 -11]
  [-12   1   1 -15]]]


10 - Adicione 2.5 a todos os valores presentes no array resultante da etapa anterior.

In [33]:
# Insira a resposta abaixo.
np_row = np_row.astype(float)
np_row[:] += 2.5

print(f"Novo arrey resultante: \n {np_row}")

Novo arrey resultante: 
 [[[  2.5   3.5   3.5   5.5]
  [  6.5   3.5   3.5   9.5]
  [ 10.5   3.5   3.5  13.5]
  [ 14.5   3.5   3.5  17.5]]

 [[  2.5   3.5   3.5  -0.5]
  [ -1.5   3.5   3.5  -4.5]
  [ -5.5   3.5   3.5  -8.5]
  [ -9.5   3.5   3.5 -12.5]]]


11 - Realize as seguintes operações:
1. Crie uma matriz com valor 3 em todas as posições com dimensionalidade (4, 2).
2. Crie uma matriz identidade de dimensionalidade (4, 4).
3. Compute o produto entre a transposta da primeira matriz e a matriz identidade, apresentando o resultado final.

In [45]:
# Insira a resposta abaixo.

# Passo 1
np_Passo1 = np.zeros([4, 2]) + 3

# Passo 2
np_I = np.eye(4)

# Passo 3
np_T = np_Passo1.T
np_Prod = np_T @ np_I

print(f"Rsultado final: \n {np_Prod}")

Rsultado final: 
 [[3. 3. 3. 3.]
 [3. 3. 3. 3.]]


12 - Realize as seguintes operações:
1. Crie uma nova matriz de valores inteiros de 25 até 49 com dimensionalidade (5,5).
2. Crie uma nova matriz com valores uniformemente espaçados entre 0 e 1 e defina a sua dimensionalidade em (5,1).
3. Concatene horizontalmente as duas matrizes criadas anteriormente.

In [70]:
# Insira a resposta abaixo.

# Passo 1
np_int = np.arange(25, 50).reshape(5, 5)
print(f"Matriz de inteiros: \n {np_int} \n")

# Passo 2
np_Un = np.linspace(0, 1, 5).reshape(5, 1)
print(f"Matriz uniforme 5 x 1: \n {np_Un} \n")

# Passo 3
np_Con = np.hstack((np_int, np_Un))
print(f"Matriz final: \n {np_Con}")

Matriz de inteiros: 
 [[25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]] 

Matriz uniforme 5 x 1: 
 [[0.  ]
 [0.25]
 [0.5 ]
 [0.75]
 [1.  ]] 

Matriz final: 
 [[25.   26.   27.   28.   29.    0.  ]
 [30.   31.   32.   33.   34.    0.25]
 [35.   36.   37.   38.   39.    0.5 ]
 [40.   41.   42.   43.   44.    0.75]
 [45.   46.   47.   48.   49.    1.  ]]


13 - Crie uma nova matriz com dimensionalidade (5,1) com números uniformemente espaçados utilizando um espaço logarítmico ao invés de um espaço linear.

In [16]:
# Insira a resposta abaixo.


14 - Crie uma função que receba um array e adicione uma borda composta de zeros nos quatro lados do array. Utilize o array resultante da questão anterior para testar o método criado.

In [17]:
# Insira a resposta abaixo.


15 - Crie um array de 36 números aleatórios oriundos de uma distribuição normal. Exiba o valor máximo, mínimo, a média e o desvio padrão desse array.

In [18]:
# Insira a resposta abaixo.
